/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homeproject;

import static java.lang.Long.max;
import static java.lang.Long.min;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowSorter;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.JSpinner;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Oana Ionel
 */
public class AdministrareProdus extends javax.swing.JFrame {

    /**
     * Creates new form AdministrareProdus
     */
    public List<Produs> generalList = new ArrayList<>();
    public static final int maxLimit = 5;

    public AdministrareProdus() {
        initComponents();
        btnGroupPriceCompare.add(rbLess);
        btnGroupPriceCompare.add(rbEqual);
        btnGroupPriceCompare.add(rbMore);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupPriceCompare = new javax.swing.ButtonGroup();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelProduse = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        tbName = new javax.swing.JTextField();
        labelPrice = new javax.swing.JLabel();
        tbPrice = new javax.swing.JTextField();
        rbMore = new javax.swing.JRadioButton();
        rbEqual = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        rbLess = new javax.swing.JRadioButton();
        labelColor = new javax.swing.JLabel();
        taColor = new javax.swing.JTextField();
        cbInStock = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        dateChooser1 = new com.toedter.calendar.JDateChooser();
        dateChooser2 = new com.toedter.calendar.JDateChooser();
        cbProductType = new javax.swing.JComboBox<>();
        labelProductType = new javax.swing.JLabel();
        btnDeleteCheckedProducts = new javax.swing.JButton();
        spinnerPage = new javax.swing.JSpinner();
        labelPage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                loadTable(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        jScrollPane1.setInheritsPopupMenu(true);

        tabelProduse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelProduse.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(tabelProduse);

        jLabel1.setText("Cautare Avansata");

        labelName.setText("Nume");

        tbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbNameActionPerformed(evt);
            }
        });

        labelPrice.setText("Pret");

        tbPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbPriceActionPerformed(evt);
            }
        });

        rbMore.setText(">");
        rbMore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMoreActionPerformed(evt);
            }
        });

        rbEqual.setText("=");
        rbEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbEqualActionPerformed(evt);
            }
        });

        btnSearch.setText("Cauta");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        rbLess.setText("<");
        rbLess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLessActionPerformed(evt);
            }
        });

        labelColor.setText("Culoare");

        taColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taColorActionPerformed(evt);
            }
        });

        cbInStock.setText("In Stoc");
        cbInStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInStockActionPerformed(evt);
            }
        });

        jLabel2.setText("Data Expirare");

        dateChooser1.setDateFormatString("yyyy-dd-MM");

        dateChooser2.setDateFormatString("yyyy-dd-MM");

        cbProductType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProductType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductTypeActionPerformed(evt);
            }
        });

        labelProductType.setText("Tip Produs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPrice, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, Short.MAX_VALUE)
                                        .addComponent(rbLess)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbEqual)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rbMore)
                                        .addGap(54, 54, 54))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tbName, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(labelColor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(taColor)
                                    .addComponent(dateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(dateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelProductType)
                            .addComponent(cbInStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(75, 75, 75))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbEqual)
                    .addComponent(rbMore)
                    .addComponent(rbLess))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taColor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelColor))
                .addGap(31, 31, 31)
                .addComponent(cbInStock)
                .addGap(12, 12, 12)
                .addComponent(dateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addComponent(dateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProductType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProductType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addGap(41, 41, 41))
        );

        btnDeleteCheckedProducts.setText("Sterge Produsele Selectate");
        btnDeleteCheckedProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCheckedProductsActionPerformed(evt);
            }
        });

        spinnerPage.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerPageStateChanged(evt);
            }
        });

        labelPage.setText("Pagina");

        jLabel4.setText("Administrare Tip Produs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(labelPage)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(btnDeleteCheckedProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labelPage)
                                    .addComponent(spinnerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeleteCheckedProducts)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnRemove)
                                .addGap(18, 18, 18)
                                .addComponent(btnModify))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AdaugareTipProdus atp = new AdaugareTipProdus();
        atp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAddActionPerformed

    private void loadTable(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loadTable
        // TODO add your handling code here:
        ProdusDAO pdao = new ProdusDAO();
        List<Produs> produse = pdao.retrieveProducts();
        refreshTable(produse, true);
    }//GEN-LAST:event_loadTable
    // determine spinner maximum number
    public int maxDetermination(List<Produs> produse) {
        if (produse.size() == 0) {
            return 1;
        }
        if (produse.size() % maxLimit == 0) {
            return (produse.size() / maxLimit);
        } else {
            return ((produse.size() / maxLimit) + 1);
        }
    }

    // populate table
    private void refreshTable(List<Produs> produse, boolean changed) {
        // array to limit list to 5 elements
        List<Produs> limitList = new ArrayList<>();

        // used for pagination
        if (changed) {
            generalList = produse;
            // SpinnerNumberModel(current spinner value, min, max, step)
            SpinnerModel moodelSpinner = new SpinnerNumberModel(1, 1, maxDetermination(produse), 1);
            spinnerPage.setModel(moodelSpinner);

        }
        //column names
        String[] columnNames = {"Nume Produs", "Pret", "Culoare", "Pe Stoc", "Data Expirare",
            "Nume Tip Produs", "Descriere", "Select"};
        //  column types for sorting the table
        final Class<?>[] columnClasses = new Class<?>[]{String.class, Double.class, String.class, String.class,
            Date.class, String.class, String.class, Boolean.class};
        // set column names
        DefaultTableModel model = new DefaultTableModel() {

            @Override
            public int getColumnCount() {
                return columnNames.length;
            }

            @Override
            public String getColumnName(int index) {
                return columnNames[index];
            }

            @Override
            public Class<?> getColumnClass(int column) {
                return columnClasses[column];
            }
        };
        // get current spinner value
        Integer currentValue = (Integer) spinnerPage.getValue();
        // populate limitList with values to be displayed on a single page
        int realMaxLimit = Math.min(produse.size(), currentValue * maxLimit);
        limitList = produse.subList((currentValue - 1) * maxLimit, realMaxLimit);
        Iterator<Produs> it = limitList.iterator();
        while (it.hasNext()) {
            Produs p = it.next();
            Object[] rowData = {p.getNumeProdus(), p.getPretProdus(),
                p.getCuloare(), Boolean.toString(p.isPeStoc()), p.getDataExpirare(),
                p.getTp().getNumeTipProdus(), p.getTp().getDescriere(), Boolean.FALSE};
            model.addRow(rowData);
        }

        tabelProduse.setModel(model);
        // sortable table
        tabelProduse.setAutoCreateRowSorter(true);
        RowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(model);
        tabelProduse.setRowSorter(sorter);
    }


    private void rbMoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMoreActionPerformed

    private void rbEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbEqualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbEqualActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        // advanced search
        String name = tbName.getText();
        String sPrice = tbPrice.getText();
        String color = taColor.getText();
        boolean inStock = cbInStock.isSelected();
        Date date1 = dateChooser1.getDate();
        Date date2 = dateChooser2.getDate();
        String comboboxProductType = cbProductType.getSelectedItem().toString();

        Double price = null;
        if (sPrice.length() > 0) {
            try {
                price = Double.parseDouble(sPrice);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(AdministrareProdus.this, "Price should be a number");
                price = null;
            }
        }

        PriceCompare priceCompare;
        if (rbLess.isSelected()) {
            priceCompare = PriceCompare.LESS;
        } else if (rbEqual.isSelected()) {
            priceCompare = PriceCompare.EQUAL;
        } else {
            priceCompare = PriceCompare.MORE;
        }

        ProdusDAO pDao = new ProdusDAO();
        List<Produs> produse = pDao.advancedSearchProducts(name, price, priceCompare, color, inStock, date1, date2, comboboxProductType);
        refreshTable(produse, true);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void tbPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbPriceActionPerformed

    private void tbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbNameActionPerformed

    private void rbLessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLessActionPerformed

    private void taColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_taColorActionPerformed

    private void cbInStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInStockActionPerformed

    private void cbProductTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductTypeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbProductTypeActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:

        ProdusDAO pdao = new ProdusDAO();
        List<String> ls = pdao.retrieveProductType();
        ls.add(0, "Any");
        cbProductType.setModel(new DefaultComboBoxModel(ls.toArray()));
    }//GEN-LAST:event_formWindowActivated

    private void btnDeleteCheckedProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCheckedProductsActionPerformed
        // TODO add your handling code here:
        Produs p = new Produs();
        ProdusDAO pdao = new ProdusDAO();
        for (int i = 0; i < tabelProduse.getRowCount(); i++) {
            Boolean value = (Boolean) tabelProduse.getValueAt(i, 7);
            if (value) {
                p.setNumeProdus((String) tabelProduse.getValueAt(i, 0));
                p.setPretProdus((double) tabelProduse.getValueAt(i, 1));
                p.setCuloare((String) tabelProduse.getValueAt(i, 2));
                p.setPeStoc(Boolean.parseBoolean((String) tabelProduse.getValueAt(i, 3)));
                p.setDataExpirare((Date) tabelProduse.getValueAt(i, 4));
                pdao.removeProductById(pdao.retrieveIdProduct(p));
            }
        }
        refreshTable(pdao.retrieveProducts(), true);
    }//GEN-LAST:event_btnDeleteCheckedProductsActionPerformed

    private void spinnerPageStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerPageStateChanged
        // TODO add your handling code here:
        refreshTable(generalList, false);
    }//GEN-LAST:event_spinnerPageStateChanged

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        StergereTipProdus stp = new StergereTipProdus();
        stp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        ModificareTipProdus mtp = new ModificareTipProdus();
        mtp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnModifyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrareProdus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrareProdus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrareProdus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrareProdus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrareProdus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDeleteCheckedProducts;
    private javax.swing.ButtonGroup btnGroupPriceCompare;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox cbInStock;
    private javax.swing.JComboBox<String> cbProductType;
    private com.toedter.calendar.JDateChooser dateChooser1;
    private com.toedter.calendar.JDateChooser dateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelColor;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPage;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JLabel labelProductType;
    private javax.swing.JRadioButton rbEqual;
    private javax.swing.JRadioButton rbLess;
    private javax.swing.JRadioButton rbMore;
    private javax.swing.JSpinner spinnerPage;
    private javax.swing.JTextField taColor;
    private javax.swing.JTable tabelProduse;
    private javax.swing.JTextField tbName;
    private javax.swing.JTextField tbPrice;
    // End of variables declaration//GEN-END:variables
}
